on: [push, pull_request]
name: Tests
jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.12.x
          - 1.13.x
          - 1.14.x
          - 1.15.x
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set git to turn off auto-converting line endings
        run: git config --global core.autocrlf false
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
